### ISSUE TITLE
Provisioning fails against cPouta

### ISSUE THREAD

**Issue by tourunen** [CSCfi/pouta-ansible-cluster#94]
There is a problem with current version of shade against cPouta nova API when creating servers with server groups. The underlying problem seems to be this shade issue: 

https://storyboard.openstack.org/#!/story/2001174

If your application can live with the increased risk of data loss,  a possible workaround is to disable server groups in tasks/vm_group_provisioning.yml by commenting out scheduler_hints:

```yaml
    volume_size: 50
#    scheduler_hints: "{{ scheduler_hints | default({}) }}"
    wait: no
```
